set -euo pipefail
source "$(dirname "$0")/../../lib/log.sh"

APP_ROOT="${APP_ROOT:-$HOME/neotree}"
APP_DIR="${APP_DIR:-$APP_ROOT/datapipeline}"
VENV_DIR="${VENV_DIR:-$APP_DIR/env}"
CRON_SCHEDULE="${DATAPIPELINE_CRON_SCHEDULE:-*/30 * * * *}"
CRON_COMMAND="${DATAPIPELINE_CRON_COMMAND:-cd $APP_DIR && env/bin/python -m kedro run --env=dev}"
CRON_MARKER_BEGIN="# BEGIN neotree datapipeline"
CRON_MARKER_END="# END neotree datapipeline"

if [ ! -d "$APP_DIR" ]; then
  log_error "Datapipeline directory not found: $APP_DIR"
  exit 1
fi

if [ ! -x "$VENV_DIR/bin/python" ]; then
  log_error "Datapipeline Python executable not found: $VENV_DIR/bin/python. Run Python setup first."
  exit 1
fi

if ! command -v crontab >/dev/null 2>&1; then
  log_error "crontab is required but not found. Install cron before configuring the datapipeline schedule."
  exit 1
fi

ensure_vim_default_editor() {
  if [ -n "${VISUAL:-}" ] || [ -n "${EDITOR:-}" ]; then
    return 0
  fi

  if ! command -v vim >/dev/null 2>&1; then
    log_warn "vim not found; leaving crontab editor unchanged"
    return 0
  fi

  export VISUAL=vim
  export EDITOR=vim

  if [ ! -f "$HOME/.selected_editor" ]; then
    {
      printf '# Generated by Neotree deployment for crontab editing.\n'
      printf 'SELECTED_EDITOR="%s"\n' "$(command -v vim)"
    } > "$HOME/.selected_editor"
    chmod 600 "$HOME/.selected_editor"
    log_info "Set vim as the default crontab editor in $HOME/.selected_editor"
  fi
}

ensure_vim_default_editor

tmp_existing="$(mktemp)"
tmp_new="$(mktemp)"
cleanup() {
  rm -f "$tmp_existing" "$tmp_new"
}
trap cleanup EXIT

crontab -l > "$tmp_existing" 2>/dev/null || true

awk -v begin="$CRON_MARKER_BEGIN" -v end="$CRON_MARKER_END" '
  $0 == begin { skip=1; next }
  $0 == end { skip=0; next }
  !skip { print }
' "$tmp_existing" > "$tmp_new"

if [ -s "$tmp_new" ]; then
  printf '\n' >> "$tmp_new"
fi

{
  printf '%s\n' "$CRON_MARKER_BEGIN"
  printf '%s %s\n' "$CRON_SCHEDULE" "$CRON_COMMAND"
  printf '%s\n' "$CRON_MARKER_END"
} >> "$tmp_new"

crontab "$tmp_new"

log_success "Datapipeline cron job installed: $CRON_SCHEDULE $CRON_COMMAND"
